---
title: "Requirements"
subtitle: "Reproducible Data Workflows with drake"
author: "Garrick Aden-Buie"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages

We'll need the following packages to get started.
Comment out or delete the lines containing any packages in `required_packages` that you already have installed on your system.

```{r eval=FALSE}
required_packages <- c(
  # "tidyverse",  #<< For data processing, etc. (you probably have this)
  "here",         #<< For sane path management
  "cowplot",      #<< For composing ggplot2 plots
  "visNetwork",   #<< For visualizing drake plans
  "drake"         #<< Because drake
)

install.packages(required_packages)
```

## Data and Materials

You can explore this workshop in a pre-loaded [RStudio cloud instance](https://rstudio.cloud/project/405721).

Or download the code and data from [github.com/gadenbuie/drake-intro](https://github.com/gadenbuie/drake-intro).

---

<details><summary>My Session Info</summary>

```{r}
devtools::session_info()
```

</details>
